Αλλαγή css για σωστή εμφάνιση backgroung image από κινητό
ioniodi/minimal-ionio pull request #44
Opened 2022-04-17 10:21 UTC by p19zing

### Σχετικό Issue
closes **ioniodi/sitegr#396**

[Link προς το demo των αλλαγών](https://p19zing-sitegr.netlify.app)  **Πρέπει να φορτωθεί από κινητό !**

### [Σχετικό Pull Request στο sitegr](https://github.com/ioniodi/sitegr/pull/400)

### Συνεργάτες
@Vuxxs , @p19vrou

### Προτεινόμενες Αλλαγές
Οι αλλαγές περιγράφονται στο pull request του sitegr (παραπάνω link)

Εδώ έγινε αλλαγή στο css της background εικόνας

### Υπενθυμίσεις
- [x] Έχω ανοίξει από πριν issue για τον καλό συντονισμό του project, το οποίο έχει πάρει το πράσινο φως με την αντίστοιχη ετικέτα
- [x] Έχω ενημερώσει το issueNo παραπάνω με τον αριθμό του αντίστοιχου θέματος, ώστε να κλείσει αυτόματα με την αποδοχή αυτού του αιτήματος
- [x] Έχω δημιουργήσει branch για τις αλλαγές

2022-04-18 09:49 UTC, Vuxxs commented
> Οι αλλαγές περιγράφονται στο pull request του sitegr (παραπάνω link)

Πρέπει να τις βάλεις και εδώ


> [Link προς το demo των αλλαγών](https://p19zing-sitegr.netlify.app) **Πρέπει να φορτωθεί από κινητό !**

Δε νομίζω ότι είναι σωστή αλλαγή, το αυθεντικό site φαίνεται να φορτώνει καλύτερα στις συσκευές μου.

2022-04-18 20:12 UTC, p19zing commented
> > Οι αλλαγές περιγράφονται στο pull request του sitegr (παραπάνω link)
> 
> Πρέπει να τις βάλεις και εδώ

Έβαλα και εδώ την περιγραφή της υλοποίησης

> 
> > [Link προς το demo των αλλαγών](https://p19zing-sitegr.netlify.app) **Πρέπει να φορτωθεί από κινητό !**
> 
> Δε νομίζω ότι είναι σωστή αλλαγή, το αυθεντικό site φαίνεται να φορτώνει καλύτερα στις συσκευές μου ενώ στο demo φαίνεται να μη φορτώνει σωστά η εικόνα

Μάλλον εννοείς ότι η εικόνα φαίνεται στο κάτω μέρος. Αυτό δεν είναι λάθος στο css, απλώς έτσι είναι η εικόνα - όπως το εξηγώ παραπάνω έγινε εσκεμμένα για να φαίνονται καλύτερα τα γράμματα.

Όπως αναφέρω στο issue, ο στόχος είναι η αντικατάσταση του iframe από εικόνα, το οποίο αν κάνεις έλεγχο της σελίδας θα δεις ότι υλοποιήθηκε. Αν έχεις να προτείνεις κάποια εικόνα που θεωρείς ότι ταιριάζει περισσότερο, μπορείς την επισυνάψεις και αν και οι υπόλοιποι τη θεωρούν πιο ταιριαστή ευχαρίστως να την αντικαταστήσω.

2022-04-21 14:46 UTC, p19zing commented
> γιατί βάζεις τις αλλαγές στο αρχείο του αρχικού θέματος αντί για το αρχείο minimal-ionio που είναι στα import?

@epidrome Μετέφερα τις css αλλαγές και το js (#ioniodi/sitegr/pull/400), στο minimal-ionio

2022-04-21 15:01 UTC, p19vrou commented
Συμφωνώ με τις παρατηρήσεις που σου έκαναν ήδη, εφόσον τις διόρθωσες από εμένα εγκρίνεται.

2022-04-30 14:30 UTC, epidrome requested changes

2022-04-30 14:30 UTC, epidrome commented on assets/js/index.js
> +if (/Mobile|Android|iP(hone|od)|IEMobile|BlackBerry|Kindle|Silk-Accelerated|(hpw|web)OS|Opera M(obi|ini)/.test(navigator.userAgent)) {
γιατί είναι σημαντικό το μοντέλο της συσκευής αντί για κάποια στοιχεία της όπως το μέγεθος της οθόνης ή και το δίκτυο της;

είναι το ίδιο ένα κινητό με οθόνη 4 ή 8 ίντσες; είναι το ίδιο ένα κινητό που είναι συνδεδεμένο σε ευρυζωνικά δίκτυο;

2022-04-30 16:15 UTC, p19zing commented on _sass/minimal-mistakes/_page.scss
> -
Το z-index θεωρώ ότι απαιτείται για να μπαίνει η εικόνα πίσω από τα γράμματα.
Το height: 180% το έβαλα για να κάνει scale η εικόνα και να φαίνεται το μαύρο της εικόνας πίσω από τα γράμματα και να κάνει πιο ωραία αντίθεση. Αλλά δεν είναι απαραίτητο όσο το z-index: -2.

2022-04-30 16:18 UTC, p19zing commented on assets/js/index.js
> +if (/Mobile|Android|iP(hone|od)|IEMobile|BlackBerry|Kindle|Silk-Accelerated|(hpw|web)OS|Opera M(obi|ini)/.test(navigator.userAgent)) {
Σωστή η παρατήρησή σας (κυρίως για τη σύνδεση σε ευρυζωνικό δίκτυο, καθώς θέλουμε να κερδίσουμε σε ταχύτητα) αλλά δεν ξέρω πως να γίνει. Για το μέγεθος της οθόνης ίσως να μπορώ να βρω κάτι σχετικό αλλά αφού το 95+ % των χρηστών έχουν smartphones περίπου 5,5-6 inches νομίζω ότι ο κώδικας είναι ικανοποιητικός

2022-04-30 16:26 UTC, p19zing commented on assets/js/index.js
> +if (/Mobile|Android|iP(hone|od)|IEMobile|BlackBerry|Kindle|Silk-Accelerated|(hpw|web)OS|Opera M(obi|ini)/.test(navigator.userAgent)) {
Επίσης δεν έχω βρει ακόμη που να βάλω την αναφορά στο index.js (ioniodi/sitegr#400)

2022-05-02 09:15 UTC, p19zing commented on assets/js/index.js
> +if (/Mobile|Android|iP(hone|od)|IEMobile|BlackBerry|Kindle|Silk-Accelerated|(hpw|web)OS|Opera M(obi|ini)/.test(navigator.userAgent)) {
@epidrome Μετά από πολλές δοκιμές κατέληξα να κάνω include το index.js στο αρχείο `_includes/scripts.html` - ελπίζω τώρα να είναι στο σωστό σημείο

2023-05-23 09:04 UTC, closed without merging